### ISSUE TITLE
install issue (potential incorrect dependency)

### ISSUE THREAD

**Issue by nico3865** [aserg-ufmg/RefDiff#3]
Hello!

I'm trying to install RefDiff and run your example (https://github.com/aserg-ufmg/RefDiff/blob/master/doc/Tutorial1.md).

When running the first chunk of example code, I get this error:

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: org.eclipse.jgit.errors.MissingObjectException: Missing unknown d94ca2b27c9e8a5fa9fe19483d58d2f2ef024606
	at refdiff.core.rm2.analysis.StructuralDiffHandler.handleException(StructuralDiffHandler.java:36)
	at refdiff.core.rm2.analysis.GitHistoryStructuralDiffAnalyzer.detectAtCommit(GitHistoryStructuralDiffAnalyzer.java:108)
	at refdiff.core.RefDiff.detectAtCommit(RefDiff.java:64)
	at refdiff.tutorial1.Main.main(Main.java:18)
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown d94ca2b27c9e8a5fa9fe19483d58d2f2ef024606
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:163)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
	at refdiff.core.rm2.analysis.GitHistoryStructuralDiffAnalyzer.detectAtCommit(GitHistoryStructuralDiffAnalyzer.java:101)
	... 2 more
`

Inside the "slf4j-api-1.7.2-sources.jar", I can't see the class "org.slf4j.impl.StaticLoggerBinder" at all.

Let me know if I'm doing something incorrectly, or if the jar should be updated to another version.

Thanks!

**Comment by saramsh** [comment]
I had the same issue but i downloaded the refdiff-core jar with all dependencies from this site: (https://jar-download.com/explore-java-source-code.php?a=refdiff-core&g=com.github.aserg-ufmg&v=0.1.1&downloadable=1) and it worked for me.

**Comment by danilofes** [comment]
I'm closing this issue as it relates to older versions of RefDiff.
